language: generic
# We need super user permissions
sudo: required
# We need a copy of a docker
services:
  - docker

before_install:
  - docker build -t eugenefacecontrol/docker-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true eugenefacecontrol/docker-udemy npm run test